//! xtask — build tasks for this workspace.
//!
//! Run with: `cargo xtask <task>`
//! Tasks are delegated to the `taskit` binary.

fn main() {
    let task = std::env::args().nth(1).unwrap_or_default();
    match task.as_str() {
        "fmt" => task_fmt(),
        "fmt-check" => task_fmt_check(),
        "lint" => task_lint(),
        "test" => task_test(),
        "ci" => task_ci(),
        "pre-commit" => task_pre_commit(),
        "pre-push" => task_pre_push(),
        other => {
            eprintln!("unknown task: {other}");
            eprintln!("available: fmt, fmt-check, lint, test, ci, pre-commit, pre-push");
            std::process::exit(1);
        }
    }
}

// --- taskit-managed ---
// The functions below were generated by `taskit init`.

fn taskit(args: &[&str]) {
    let status = std::process::Command::new("taskit")
        .args(args)
        .status()
        .unwrap_or_else(|_| {
            std::process::Command::new("cargo")
                .args(["run", "-p", "taskit", "--"])
                .args(args)
                .status()
                .expect("failed to run taskit")
        });
    if !status.success() {
        std::process::exit(status.code().unwrap_or(1));
    }
}

fn task_fmt() {
    taskit(&["fmt"])
}
fn task_fmt_check() {
    taskit(&["fmt", "--check"])
}
fn task_lint() {
    taskit(&["lint"])
}
fn task_test() {
    taskit(&["test"])
}
fn task_ci() {
    taskit(&["ci"])
}
fn task_pre_commit() {
    taskit(&["pre-commit"])
}
fn task_pre_push() {
    taskit(&["pre-push"])
}
// --- end taskit-managed ---
